"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Bot, Check, Clock3, Edit3, Package, Send, Store } from "lucide-react";
import { useApp } from "@/components/app-provider";

export default function ProductDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { state, publishItem, updateInventory } = useApp();
  const item = state.inventory.find((entry) => entry.id === id);
  if (!item) return <div className="page-wrap"><div className="empty"><h2>Product not found</h2><Link href="/inventory" className="btn btn-primary">Back to inventory</Link></div></div>;
  const listing = state.listings.find((entry) => entry.inventoryItemId === id);
  const correction = state.corrections.find((entry) => entry.inventoryItemId === id);
  return <div className="page-wrap"><Link href="/inventory" className="btn btn-ghost" style={{ paddingLeft: 0, marginBottom: 12 }}><ArrowLeft size={16} />Back to inventory</Link><div className="page-header"><div><div style={{ display: "flex", alignItems: "center", gap: 10 }}><h1>{item.name}</h1><span className={`badge ${item.quantity <= item.lowStockThreshold ? "badge-amber" : "badge-green"}`}>{item.quantity <= item.lowStockThreshold ? "Low stock" : "In stock"}</span></div><p>{item.brand || "Unbranded"} · {item.category}</p></div><div style={{ display: "flex", gap: 9 }}>{listing?.isPublished && <Link href={`/store/${state.business.slug}`} className="btn btn-secondary"><Store size={16} />View store</Link>}<button className="btn btn-primary" onClick={() => item.price ? publishItem(item.id) : alert("Set a price before publishing.")}><Send size={16} />{listing?.isPublished ? "Update listing" : "Publish product"}</button></div></div>
    <div className="grid-2" style={{ gridTemplateColumns: "1.2fr .8fr" }}><section className="card" style={{ padding: 24 }}><div style={{ display: "flex", justifyContent: "space-between" }}><h2 className="section-title">Product information</h2><button className="btn btn-ghost" onClick={() => { const quantity = prompt("Update quantity", String(item.quantity)); if (quantity !== null) updateInventory(item.id, { quantity: Number(quantity) }); }}><Edit3 size={15} />Edit stock</button></div><div className="grid-2" style={{ marginTop: 22 }}>{[{ label: "Current stock", value: `${item.quantity} ${item.unit}` }, { label: "Price", value: item.price ? `₹${item.price}` : "Not set" }, { label: "Low-stock threshold", value: `${item.lowStockThreshold} ${item.unit}` }, { label: "Source", value: item.source.replace("_", " ") }].map((data) => <div className="subtle-card" style={{ padding: 16 }} key={data.label}><span className="muted" style={{ fontSize: 11 }}>{data.label}</span><strong style={{ display: "block", marginTop: 7, textTransform: data.label === "Source" ? "capitalize" : undefined }}>{data.value}</strong></div>)}</div><div style={{ marginTop: 24 }}><span className="label">Description</span><p className="muted" style={{ lineHeight: 1.7 }}>{item.description}</p></div></section>
      <aside style={{ display: "grid", gap: 20 }}><section className="card" style={{ padding: 22 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div className="empty-icon" style={{ margin: 0, width: 38, height: 38 }}><Bot size={18} /></div><div><h2 className="section-title">AI extraction</h2><span className="muted" style={{ fontSize: 11 }}>{item.source === "ai_scan" ? "Generated from a product scan" : "Not AI-generated"}</span></div></div>{item.aiConfidence ? <><div style={{ display: "flex", justifyContent: "space-between", marginTop: 22, fontSize: 12 }}><span>Confidence</span><strong>{Math.round(item.aiConfidence * 100)}%</strong></div><div style={{ height: 7, background: "#edf1ee", borderRadius: 99, marginTop: 8 }}><i style={{ display: "block", height: "100%", width: `${item.aiConfidence * 100}%`, background: "#73AB95", borderRadius: 99 }} /></div></> : <p className="muted" style={{ fontSize: 12, marginTop: 18 }}>This item was added {item.source.replace("_", " ")}.</p>}</section>
      <section className="card" style={{ padding: 22 }}><h2 className="section-title">Storefront status</h2><div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 18 }}><div className="empty-icon" style={{ margin: 0, width: 38, height: 38, background: listing?.isPublished ? "#F6F6F6" : "#f1f3f2" }}>{listing?.isPublished ? <Check size={18} /> : <Clock3 size={18} />}</div><div><strong style={{ fontSize: 13 }}>{listing?.isPublished ? "Published and visible" : listing ? "Draft awaiting approval" : "Inventory only"}</strong><p className="muted" style={{ fontSize: 11, margin: "4px 0 0" }}>{listing?.isPublished ? "Customers can order this product." : "Publish when the details are ready."}</p></div></div></section></aside></div>
    {correction && <section className="card" style={{ marginTop: 20, padding: 24 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><Package size={18} color="#2C645B" /><h2 className="section-title">Human correction history</h2></div><p className="muted" style={{ fontSize: 12 }}>Your review changed the AI output before this product was saved.</p><div className="grid-2" style={{ marginTop: 16 }}><pre className="subtle-card" style={{ padding: 16, overflow: "auto", fontSize: 11 }}>{JSON.stringify(correction.original, null, 2)}</pre><pre className="subtle-card" style={{ padding: 16, overflow: "auto", fontSize: 11 }}>{JSON.stringify(correction.corrected, null, 2)}</pre></div></section>}
  </div>;
}

