"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, Play, Zap } from "lucide-react";
import { useApp } from "@/components/app-provider";
import { StatusBadge } from "@/components/status-badge";

export default function AutomationsPage() {
  const { state } = useApp();
  const success = state.executions.filter((item) => item.status === "success").length;
  const waiting = state.executions.filter((item) => item.status === "waiting_for_human").length;
  return <div className="page-wrap"><div className="page-header"><div><div className="eyebrow">Agentic operations</div><h1>Automations</h1><p>See how events move through your business, step by step.</p></div></div>
    <div className="grid-3" style={{ marginBottom: 20 }}><div className="card metric"><div className="metric-label">Active workflows</div><div className="metric-value">{state.workflows.filter((item) => item.isActive).length}</div><small className="muted">Watching business events</small></div><div className="card metric"><div className="metric-label">Successful runs</div><div className="metric-value">{success}</div><small className="muted">Completed without errors</small></div><div className="card metric"><div className="metric-label">Waiting for you</div><div className="metric-value">{waiting}</div><small className="muted">Human approval checkpoints</small></div></div>
    <section className="grid-3">{state.workflows.map((workflow) => { const runs = state.executions.filter((item) => item.workflowId === workflow.id); const latest = runs[0]; return <Link href={`/automations/${workflow.id}`} className="card" style={{ padding: 22, display: "flex", flexDirection: "column", minHeight: 275 }} key={workflow.id}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}><div className="empty-icon" style={{ margin: 0, width: 42, height: 42 }}><Zap size={19} /></div><span className="badge badge-green">Active</span></div><h2 style={{ fontSize: 17, letterSpacing: "-.025em", margin: "19px 0 8px" }}>{workflow.name}</h2><p className="muted" style={{ fontSize: 12, lineHeight: 1.6, margin: 0 }}>{workflow.description}</p><div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 16 }}><span className="badge badge-gray">{workflow.triggerType.replaceAll("_", " ")}</span><span className="muted" style={{ fontSize: 10 }}>{workflow.nodeNames.length} nodes</span></div><div style={{ marginTop: "auto", paddingTop: 18, borderTop: "1px solid #e8ece9", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span className="muted" style={{ fontSize: 11 }}>{runs.length} execution{runs.length === 1 ? "" : "s"}{latest && <> · <StatusBadge status={latest.status} /></>}</span><ArrowRight size={16} color="#2C645B" /></div></Link>})}</section>
    <section className="card" style={{ marginTop: 20 }}><div style={{ padding: 20, borderBottom: "1px solid #e4e9e5" }}><h2 className="section-title">Recent executions</h2><p className="muted" style={{ fontSize: 12, margin: "5px 0 0" }}>An audit trail of automated business activity.</p></div>{state.executions.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Workflow</th><th>Trigger</th><th>Status</th><th>Steps</th><th>Started</th><th /></tr></thead><tbody>{state.executions.map((execution) => <tr key={execution.id}><td><strong>{state.workflows.find((item) => item.id === execution.workflowId)?.name}</strong></td><td><span className="badge badge-gray">{execution.trigger.replaceAll("_", " ")}</span></td><td><StatusBadge status={execution.status} /></td><td>{execution.nodes.length}</td><td className="muted">{new Date(execution.startedAt).toLocaleString()}</td><td><Link className="btn btn-ghost" href={`/automations/${execution.workflowId}`}><ArrowRight size={15} /></Link></td></tr>)}</tbody></table></div> : <div className="empty"><Play /><p>Run a scan or accept an order to create a trace.</p></div>}</section>
  </div>;
}

